export const CHANGE_STATE_BOARDS = "CHANGE_STATE_BOARDS";

export const GET_BOARDS = "GET_BOARDS";

export const DELETE_BOARD = "DELETE_BOARD";

export const ADD_BOARD = "ADD_BOARD";

export const ADD_TASK_BOARD = "ADD_TASK_BOARD";

export const CHANGE_STATE_TASK_MENU = "CHANGE_STATE_TASK_MENU";

export const ADD_TASK_TITLE = "ADD_TASK_TITLE";

export const GET_TASK_LIST = "GET_TASK_LIST";

export const SET_SELECT_BOARD = "SET_SELECT_BOARD";

export const ADD_COMMENT = "ADD_COMMENT";

export const HANDLE_DROP = "HANDLE_DROP";

export const DELETE_COMMENT = "DELETE_COMMENT";
